// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: digestor.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Digestor_DigestMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var toDigest: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Digestor_DigestedMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var digested: String = String()

  var wasDigested: Bool = false

  var digestThis: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "digestor"

extension Digestor_DigestMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DigestMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ToDigest"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.toDigest)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.toDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.toDigest, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Digestor_DigestMessage, rhs: Digestor_DigestMessage) -> Bool {
    if lhs.toDigest != rhs.toDigest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Digestor_DigestedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DigestedMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Digested"),
    2: .same(proto: "WasDigested"),
    3: .same(proto: "DigestThis"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.digested)
      case 2: try decoder.decodeSingularBoolField(value: &self.wasDigested)
      case 3: try decoder.decodeSingularStringField(value: &self.digestThis)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.digested.isEmpty {
      try visitor.visitSingularStringField(value: self.digested, fieldNumber: 1)
    }
    if self.wasDigested != false {
      try visitor.visitSingularBoolField(value: self.wasDigested, fieldNumber: 2)
    }
    if !self.digestThis.isEmpty {
      try visitor.visitSingularStringField(value: self.digestThis, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Digestor_DigestedMessage, rhs: Digestor_DigestedMessage) -> Bool {
    if lhs.digested != rhs.digested {return false}
    if lhs.wasDigested != rhs.wasDigested {return false}
    if lhs.digestThis != rhs.digestThis {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
